# Server config
server.port=8085

# Application name
spring.application.name=API-GATEWAY

# Eureka config
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Disable automatic service discovery routing
spring.cloud.gateway.discovery.locator.enabled=false

# Manual routes
spring.cloud.gateway.routes[0].id=USERSERVICE
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=RATINGSERVICE
spring.cloud.gateway.routes[1].uri=lb://RATINGSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/ratings/**

spring.cloud.gateway.routes[2].id=HOTELSERVICE
spring.cloud.gateway.routes[2].uri=lb://HOTELSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/hotels/**,/staffs/**
